resources:
  - kind: project
    selector:
      query: 'true'
      defaultTeam: false
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"bitbucketProjectBlueprint"'
          properties:
            description: .description
            key: .key
            public: .public
            type: .type
            links: .links
